#!/usr/bin/env python3
"""Manual E2E test script for SquadX task execution.

This script runs a complete task execution flow locally to validate:
1. Orchestrator graph execution
2. Agent sandbox execution
3. Code generation
4. Git commit

Usage:
    python scripts/run_e2e_test.py [--with-sandbox] [--task-description "..."]

Requirements:
    - Docker running (for sandbox mode)
    - squadx/agent:latest image built
    - LLM API key configured (OPENAI_API_KEY or ANTHROPIC_API_KEY)
"""

import argparse
import asyncio
import json
import os
import shutil
import sys
import tempfile
from datetime import datetime
from pathlib import Path

# Add parent directory to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent))

from rich.console import Console
from rich.panel import Panel
from rich.progress import Progress, SpinnerColumn, TextColumn
from rich.table import Table
from rich.syntax import Syntax

console = Console()


async def run_e2e_test(
    task_description: str,
    with_sandbox: bool = False,
    workspace_path: str | None = None,
    verbose: bool = False,
):
    """Run the E2E test with the orchestrator."""
    from squadx_client.orchestrator.graph import create_orchestrator
    from squadx_client.orchestrator.state import OrchestratorState
    from squadx_client.config import settings

    # Create workspace
    if workspace_path:
        workspace = Path(workspace_path)
        workspace.mkdir(parents=True, exist_ok=True)
    else:
        workspace = Path(tempfile.mkdtemp(prefix="squadx-e2e-"))

    console.print(f"\n[bold blue]Workspace:[/] {workspace}")

    # Initialize git repo
    os.system(f'cd "{workspace}" && git init -q 2>/dev/null')
    os.system(f'cd "{workspace}" && git config user.email "test@squadx.dev" 2>/dev/null')
    os.system(f'cd "{workspace}" && git config user.name "SquadX E2E Test" 2>/dev/null')

    # Create initial commit
    readme = workspace / "README.md"
    readme.write_text("# E2E Test Project\n\nGenerated by SquadX E2E test.\n")
    os.system(f'cd "{workspace}" && git add . && git commit -q -m "Initial commit" 2>/dev/null')

    # Configure settings
    settings.workspace_path = str(workspace)
    settings.enable_sandbox = with_sandbox

    # Create task
    task = {
        "id": 9999,
        "title": "E2E Test Task",
        "description": task_description,
        "status": "IN_PROGRESS",
        "assignedAgentType": "fullstack",
    }

    console.print(Panel(
        f"[bold]{task['title']}[/]\n\n{task['description']}",
        title="Task",
        border_style="green"
    ))

    # Create initial state
    initial_state = OrchestratorState(
        task_id=task["id"],
        task=task,
    )

    # Create orchestrator
    graph = create_orchestrator()

    # Run with progress tracking
    start_time = datetime.now()

    console.print("\n[bold yellow]Starting orchestration...[/]\n")

    try:
        with Progress(
            SpinnerColumn(),
            TextColumn("[progress.description]{task.description}"),
            console=console,
        ) as progress:
            task_progress = progress.add_task("Running orchestrator...", total=None)

            # Stream the execution
            final_state = None
            async for state in graph.astream(initial_state):
                # Get the current node
                node_name = list(state.keys())[0] if state else "unknown"
                node_state = state.get(node_name, {})

                progress.update(task_progress, description=f"[cyan]{node_name}[/] node...")

                if verbose:
                    console.print(f"  [dim]Node: {node_name}[/]")
                    if node_state.get("plan"):
                        console.print(f"  [dim]Subtasks: {len(node_state['plan'].subtasks)}[/]")

                final_state = node_state

            progress.update(task_progress, description="[green]Completed![/]")

    except Exception as e:
        console.print(f"\n[bold red]Error:[/] {e}")
        if verbose:
            import traceback
            console.print(traceback.format_exc())
        return False

    end_time = datetime.now()
    duration = (end_time - start_time).total_seconds()

    # Display results
    console.print("\n" + "=" * 60)
    console.print("[bold green]E2E Test Completed[/]")
    console.print("=" * 60)

    # Metrics table
    if final_state and hasattr(final_state, "get"):
        metrics = final_state.get("metrics")
        if metrics:
            table = Table(title="Execution Metrics")
            table.add_column("Metric", style="cyan")
            table.add_column("Value", style="green")

            summary = metrics.to_summary() if hasattr(metrics, "to_summary") else {}
            table.add_row("Duration", f"{duration:.2f}s")
            table.add_row("Total Tokens", str(summary.get("tokens", {}).get("total", "N/A")))
            table.add_row("Cost (USD)", f"${summary.get('cost_usd', 0):.4f}")
            table.add_row("Tool Calls", str(summary.get("tool_calls", 0)))
            table.add_row("Files Modified", str(summary.get("files_modified", 0)))

            if summary.get("subtasks"):
                table.add_row(
                    "Subtasks",
                    f"{summary['subtasks'].get('successful', 0)} / {summary['subtasks'].get('total', 0)}"
                )

            console.print(table)

        # Show final result
        final_result = final_state.get("final_result")
        if final_result:
            console.print(Panel(
                final_result,
                title="Final Result",
                border_style="blue"
            ))

        # Show git info
        git_branch = final_state.get("git_branch")
        git_commit = final_state.get("git_commit")
        if git_branch or git_commit:
            console.print(f"\n[bold]Git:[/]")
            if git_branch:
                console.print(f"  Branch: [cyan]{git_branch}[/]")
            if git_commit:
                console.print(f"  Commit: [cyan]{git_commit}[/]")

    # List generated files
    console.print(f"\n[bold]Generated Files in {workspace}:[/]")
    for f in sorted(workspace.rglob("*")):
        if f.is_file() and ".git" not in str(f):
            rel_path = f.relative_to(workspace)
            size = f.stat().st_size
            console.print(f"  {rel_path} ({size} bytes)")

            # Show Python files content
            if f.suffix == ".py" and verbose:
                code = f.read_text()
                console.print(Syntax(code, "python", line_numbers=True))

    # Cleanup prompt
    if not workspace_path:
        console.print(f"\n[dim]Workspace: {workspace}[/]")
        console.print("[dim]Run with --workspace to specify a persistent directory[/]")

    return True


def main():
    parser = argparse.ArgumentParser(description="Run SquadX E2E test")
    parser.add_argument(
        "--with-sandbox",
        action="store_true",
        help="Run with Docker sandbox (requires squadx/agent:latest image)"
    )
    parser.add_argument(
        "--task",
        "-t",
        type=str,
        default="""Create a simple Python calculator module:

1. Create a file called 'calculator.py' with:
   - An 'add' function that adds two numbers
   - A 'subtract' function that subtracts two numbers
   - A 'multiply' function that multiplies two numbers
   - A 'divide' function that divides two numbers (handle division by zero)

2. Create a file called 'test_calculator.py' with:
   - Unit tests for all four functions
   - At least 2 test cases per function

3. Include proper docstrings and type hints.""",
        help="Task description to execute"
    )
    parser.add_argument(
        "--workspace",
        "-w",
        type=str,
        help="Path to workspace directory (default: temp directory)"
    )
    parser.add_argument(
        "--verbose",
        "-v",
        action="store_true",
        help="Show verbose output"
    )

    args = parser.parse_args()

    # Check for API key
    if not os.environ.get("OPENAI_API_KEY") and not os.environ.get("ANTHROPIC_API_KEY"):
        console.print("[bold red]Error:[/] No LLM API key found.")
        console.print("Set OPENAI_API_KEY or ANTHROPIC_API_KEY environment variable.")
        sys.exit(1)

    console.print(Panel(
        "[bold]SquadX E2E Test Runner[/]\n\n"
        f"Sandbox: {'[green]Enabled[/]' if args.with_sandbox else '[yellow]Disabled[/]'}\n"
        f"Verbose: {'[green]Yes[/]' if args.verbose else '[dim]No[/]'}",
        border_style="blue"
    ))

    success = asyncio.run(run_e2e_test(
        task_description=args.task,
        with_sandbox=args.with_sandbox,
        workspace_path=args.workspace,
        verbose=args.verbose,
    ))

    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
