apiVersion: v1
kind: Service
metadata:
  name: {{ include "squadx.fullname" . }}-backend
  labels:
    {{- include "squadx.componentLabels" (dict "context" . "component" "backend") | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
      protocol: TCP
  selector:
    {{- include "squadx.selectorLabels" (dict "context" . "component" "backend") | nindent 4 }}
