{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "squadx.fullname" . }}-ingress
  labels:
    {{- include "squadx.labels" . | nindent 4 }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
        - {{ .Values.ingress.hosts.frontend }}
        - {{ .Values.ingress.hosts.backend }}
      secretName: {{ .Values.ingress.tls.secretName }}
  rules:
    - host: {{ .Values.ingress.hosts.frontend }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "squadx.fullname" . }}-frontend
                port:
                  number: {{ .Values.frontend.service.port }}
    - host: {{ .Values.ingress.hosts.backend }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "squadx.fullname" . }}-backend
                port:
                  number: {{ .Values.backend.service.port }}
{{- end }}
